{% set name = "urlpath" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/urlpath-{{ version }}.tar.gz
  sha256: e54c0c82db4894a7217772150bdbc01413794576996e7834f81d67f22359c9d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - requests

test:
  imports:
    - urlpath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brandonschabell/urlpath
  summary: Object-oriented URL from `urllib.parse` and `pathlib`
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
