{% set name = "urlpath" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/urlpath-{{ version }}.tar.gz
  sha256: 321b932709982079e71deddb4af56ffe3447a9596faa895de19cf0cbee23b239

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - requests

test:
  imports:
    - urlpath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brandonschabell/urlpath
  summary: Object-oriented URL from `urllib.parse` and `pathlib`
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
